defmodule Averziano.Repo.Migrations.AddClientNotes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:client_notes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :kind, :text, null: false
      add :title, :text
      add :body, :text, null: false
      add :noted_on, :date

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :client_id,
          references(:users,
            column: :id,
            name: "client_notes_client_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :coach_id,
          references(:users,
            column: :id,
            name: "client_notes_coach_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :program_id,
          references(:programs,
            column: :id,
            name: "client_notes_program_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end
  end

  def down do
    drop constraint(:client_notes, "client_notes_program_id_fkey")

    drop constraint(:client_notes, "client_notes_coach_id_fkey")

    drop constraint(:client_notes, "client_notes_client_id_fkey")

    drop table(:client_notes)
  end
end
