defmodule Averziano.Repo.Migrations.AddCoachConsole do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:programs) do
      add :days, {:array, :map}, null: false, default: []
      add :published_at, :utc_datetime_usec
      add :template_id, :uuid
      remove :days_per_week
    end

    create table(:templates, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:programs) do
      modify :template_id,
             references(:templates,
               column: :id,
               name: "programs_template_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    alter table(:templates) do
      add :name, :text, null: false
      add :weeks_count, :bigint, null: false, default: 4
      add :days, {:array, :map}, null: false, default: []

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :coach_id,
          references(:users,
            column: :id,
            name: "templates_coach_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    alter table(:training_sessions) do
      add :coach_comment, :text
      add :reviewed_at, :utc_datetime_usec
    end

    alter table(:users) do
      add :role, :text, null: false, default: "client"
      add :phone, :text
      add :invited_at, :utc_datetime_usec

      add :coach_id,
          references(:users,
            column: :id,
            name: "users_coach_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end
  end

  def down do
    drop constraint(:users, "users_coach_id_fkey")

    alter table(:users) do
      remove :coach_id
      remove :invited_at
      remove :phone
      remove :role
    end

    alter table(:training_sessions) do
      remove :reviewed_at
      remove :coach_comment
    end

    drop constraint(:templates, "templates_coach_id_fkey")

    alter table(:templates) do
      remove :coach_id
      remove :updated_at
      remove :inserted_at
      remove :days
      remove :weeks_count
      remove :name
    end

    drop constraint(:programs, "programs_template_id_fkey")

    alter table(:programs) do
      modify :template_id, :uuid
    end

    drop table(:templates)

    alter table(:programs) do
      add :days_per_week, :bigint, null: false
      remove :template_id
      remove :published_at
      remove :days
    end
  end
end
