defmodule Averziano.Repo.Migrations.AddClientEquipment do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:client_equipment, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :citext, null: false
      add :details, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :client_id,
          references(:users,
            column: :id,
            name: "client_equipment_client_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:client_equipment, [:client_id, :name],
             name: "client_equipment_unique_name_per_client_index"
           )

    alter table(:client_equipment) do
      add :coach_id,
          references(:users,
            column: :id,
            name: "client_equipment_coach_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end
  end

  def down do
    drop constraint(:client_equipment, "client_equipment_coach_id_fkey")

    drop constraint(:client_equipment, "client_equipment_client_id_fkey")

    alter table(:client_equipment) do
      remove :coach_id
    end

    drop_if_exists unique_index(:client_equipment, [:client_id, :name],
                     name: "client_equipment_unique_name_per_client_index"
                   )

    drop table(:client_equipment)
  end
end
