defmodule Averziano.Repo.Migrations.AddAuthentication do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tokens, primary_key: false) do
      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :extra_data, :map
      add :purpose, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :subject, :text, null: false
      add :jti, :text, null: false, primary_key: true
    end

    create index(:users, [:role],
             name: "users_single_coach_index",
             unique: true,
             where: "role = 'coach'"
           )
  end

  def down do
    drop_if_exists index(:users, [:role], name: "users_single_coach_index")

    drop table(:tokens)
  end
end
