defmodule Averziano.Repo.Migrations.AddTraining do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:exercises, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :position, :bigint, null: false
      add :name, :text, null: false
      add :kind, :text, null: false
      add :sets_count, :bigint, null: false
      add :target_reps, :bigint
      add :target_load_kg, :decimal
      add :target_seconds, :bigint
      add :sequence, {:array, :bigint}
      add :sequence_rest_seconds, :bigint
      add :rest_seconds, :bigint, null: false, default: 90
      add :notes, :text
      add :videos, {:array, :map}, null: false, default: []
      add :target_updated_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :session_id, :uuid, null: false
    end

    create table(:programs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :starts_on, :date, null: false
      add :ends_on, :date, null: false
      add :weeks_count, :bigint, null: false
      add :days_per_week, :bigint, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :client_id,
          references(:users,
            column: :id,
            name: "programs_client_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :coach_id,
          references(:users,
            column: :id,
            name: "programs_coach_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create table(:set_logs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :set_number, :bigint, null: false
      add :reps, :bigint
      add :load_kg, :decimal
      add :seconds, :bigint
      add :outcome, :text
      add :note, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :exercise_id,
          references(:exercises,
            column: :id,
            name: "set_logs_exercise_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:set_logs, [:exercise_id, :set_number],
             name: "set_logs_unique_set_number_index"
           )

    create table(:training_sessions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:exercises) do
      modify :session_id,
             references(:training_sessions,
               column: :id,
               name: "exercises_session_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:training_sessions) do
      add :week_number, :bigint, null: false
      add :day_label, :text, null: false
      add :title, :text, null: false
      add :scheduled_on, :date, null: false
      add :coach_note, :text
      add :client_note, :text
      add :completed_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :program_id,
          references(:programs,
            column: :id,
            name: "training_sessions_program_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end
  end

  def down do
    drop constraint(:training_sessions, "training_sessions_program_id_fkey")

    alter table(:training_sessions) do
      remove :program_id
      remove :updated_at
      remove :inserted_at
      remove :completed_at
      remove :client_note
      remove :coach_note
      remove :scheduled_on
      remove :title
      remove :day_label
      remove :week_number
    end

    drop constraint(:exercises, "exercises_session_id_fkey")

    alter table(:exercises) do
      modify :session_id, :uuid
    end

    drop table(:training_sessions)

    drop constraint(:set_logs, "set_logs_exercise_id_fkey")

    drop_if_exists unique_index(:set_logs, [:exercise_id, :set_number],
                     name: "set_logs_unique_set_number_index"
                   )

    drop table(:set_logs)

    drop constraint(:programs, "programs_coach_id_fkey")

    drop constraint(:programs, "programs_client_id_fkey")

    drop table(:programs)

    drop table(:exercises)
  end
end
